import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/organisms/footer/Footer";
import FeatureGrid from "@/components/organisms/FeatureGrid/FeatureGrid";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <FeatureGrid />
        <Footer />
      </body>
    </html>
  );
}
